# Generated by Django 2.2.1 on 2019-05-22 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slife', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
