# Generated by Django 2.2.1 on 2019-06-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slife', '0002_auto_20190522_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, upload_to='categories'),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.FileField(blank=True, upload_to='options'),
        ),
    ]
