# Generated by Django 2.2.1 on 2019-07-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Slife', '0003_auto_20190625_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, upload_to='options'),
        ),
    ]
