# Generated by Django 2.2.1 on 2019-09-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slife', '0009_auto_20190819_1239'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
