# Generated by Django 2.2.1 on 2019-11-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Slife', '0011_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
